"""add project_status

Revision ID: 8d2be5840144
Revises: fdaaac176362
Create Date: 2026-01-02 20:23:24.404054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2be5840144'
down_revision: Union[str, Sequence[str], None] = 'fdaaac176362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ add column as nullable
    op.add_column(
        'projects',
        sa.Column('print_status', sa.String(length=20), nullable=True)
    )

    # 2️⃣ set default value for existing rows
    op.execute(
        "UPDATE projects SET print_status = 'Pending' WHERE print_status IS NULL"
    )

    # 3️⃣ enforce NOT NULL
    op.alter_column(
        'projects',
        'print_status',
        nullable=False
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'print_status')
    # ### end Alembic commands ###
