"""add print completed audit columns

Revision ID: a7671b55231f
Revises: 95938797dc74
Create Date: 2026-08-22 01:39:34.718396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7671b55231f'
down_revision: Union[str, Sequence[str], None] = '95938797dc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('print_completed_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('print_completed_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'print_completed_by')
    op.drop_column('projects', 'print_completed_at')
    # ### end Alembic commands ###
