"""add customers table and project lifecycle fields

Revision ID: db0a7c30cc4a
Revises: 22bf50400ead
Create Date: 2026-08-19 20:32:13.489763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0a7c30cc4a'
down_revision: Union[str, Sequence[str], None] = '22bf50400ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.CheckConstraint("contact_number ~ '^\\+?[0-9]{10,15}$'", name='customer_phone_format_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.alter_column('invoices_v1', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('projects', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('design_completed_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('design_completed_by', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('delivered_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.drop_column('projects', 'delivered_by')
    op.drop_column('projects', 'delivered_at')
    op.drop_column('projects', 'design_completed_by')
    op.drop_column('projects', 'design_completed_at')
    op.drop_column('projects', 'customer_id')
    op.alter_column('invoices_v1', 'invoice_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
