"""remove_redundant_columns

Revision ID: e792fb0de646
Revises: 8d2be5840144
Create Date: 2026-01-25 18:12:04.480179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e792fb0de646'
down_revision: Union[str, Sequence[str], None] = '8d2be5840144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_status')
    op.drop_column('projects', 'height')
    op.drop_column('projects', 'width')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('project_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
